name: sm-system
services:
  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    networks:
      - sms-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes: []
    networks:
      - sms-network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - sms-network
    depends_on:
      - backend

volumes:
  mongo_data:
  frontend_build:

networks:
  sms-network:
    driver: bridge