name: sm-system
services:
  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    networks:
      - sms-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "127.0.0.1:4000:4000"
    networks:
      - sms-network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_SERVER_URL=http://103.159.2.149/api/v1
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - frontend_build:/srv
    networks:
      - sms-network
    depends_on:
      - backend

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - frontend_build:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - sms-network

volumes:
  mongo_data:
  frontend_build:
  caddy_data:
  caddy_config:

networks:
  sms-network:
    driver: bridge