name: sm-system

services:
  mongo:
    image: mongo:8.0.4
    volumes:
      - mongo_data:/data/db
    networks:
      - sms-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes: [] # Corrected: Explicitly defined as an empty list
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - sms-network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - sms-network
    ports:
      - 5173:5173
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  mongo_data:
  frontend_build:

networks:
  sms-network:
    driver: bridge