version: '3.8'
name: sm-system

services:
  mongo:
    image: mongo:8.0.4
    volumes:
      - mongo_data:/data/db
    networks:
      - sms-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sms-backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - 3000:3000
    networks:
      - sms-network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_SERVER_URL=http://103.159.2.149/api/v1
    container_name: sms-frontend
    restart: unless-stopped
    networks:
      - sms-network
  nginx:
    image: nginx:1.24.0-alpine
    container_name: sms-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/dist:/usr/share/nginx/html 
    depends_on:
      - frontend
      - backend
    networks:
      - sms-network
volumes:
  mongo_data:

networks:
  sms-network:
    driver: bridge